### ISSUE TITLE
Split repos stars in "n" slices

### ISSUE THREAD

**Issue by meriadec** [SIGSEV/Starveller#11]
Similar to [getBars](https://github.com/SIGSEV/Starveller/blob/master/src/helpers/repos.js#L12), this function must be pure, and return an array containing n elements, but representing the entire history of the repo. So the stars must be groupped by an amount of days, to make the final array have the right number of elements.

**Comment by balthazar** [comment]
The route will be `/:org/:name/fullbars`

**Comment by meriadec** [comment]
we dont need any routes, just a pure function.
we also need to delete this api route (will not be consumed by the client) https://github.com/SIGSEV/Starveller/blob/master/src/api/index.js#L55

**Comment by balthazar** [comment]
![tumblr_n3ewcyhfga1smzuk1o1_500](https://cloud.githubusercontent.com/assets/6033345/12395334/4692161a-be01-11e5-9dc8-91fa065cf1ea.gif)

**Comment by meriadec** [comment]
not a good idea.
this is better: https://en.wikipedia.org/wiki/Linear_regression
