### ISSUE TITLE
add `languages` to repo summary...

### ISSUE THREAD

**Issue by meriadec** [SIGSEV/Starveller#13]
which will obviously be the list of languages used in the repo

**Comment by meriadec** [comment]
Dont you think the list of languages should be an array? Or is it better to store only the main language?

**Comment by balthazar** [comment]
I think we only have access to the main language using the API, but I might be wrong? Do you know any h4ck?

**Comment by meriadec** [comment]
Ok no problem! :dancers:

**Comment by meriadec** [comment]
Ok, just checked on doc, and it seems to send multiples languages for a repo: https://developer.github.com/v3/repos/#list-languages

so what dyou think?

**Comment by balthazar** [comment]
Would require an extra call for each repo. If you think the data is interesting we could do that yeah, but I don't want to be polluted by TypeScript based repos when I choose to see pure JavaScript.
