### ISSUE TITLE
Fetch trending github repos and display them in home

### ISSUE THREAD

**Issue by meriadec** [SIGSEV/Starveller#24]
- [x] refactor naming of actual "trending" entities, which has to be called "featured"
  - [x] in reducer
  - [x] in api
  - [x] in actions
  - [x] in components
- [x] proxy the request to github api for trending repos (all languages)
- [x] display them in homepage
- [x] maybe cache the trending repos (in memory should be sufficient) to avoid too much requests to github

**Comment by balthazar** [comment]
Actually I missed that the footer should not be gray when not one Home, it's ugly.
