### ISSUE TITLE
Improve cron refetch performance

### ISSUE THREAD

**Issue by balthazar** [SIGSEV/Starveller#27]
While this implicate some inaccuracies if people unstar massively, we think that this is an extreme and thus pretty rare event, that we will ignore.

Manual refresh could still be done by the SIGSEV members if 

 ![inaccurate](http://cdn.meme.am/instances2/500x/4400919.jpg)

**Comment by meriadec** [comment]
I have a repo in mind which it would make me very happy if people started to massively unstar it...
