### ISSUE TITLE
implement sockets

### ISSUE THREAD

**Issue by meriadec** [SIGSEV/Starveller#3]
- [x] implement a basic socket ping/pong between front and back
- [x] make it work in prod mode too
- [x] send events to all users when a repo finished to update his stars. it could be cool to send a msg when the repo state change, like `repo.syncing` and `repo.synced` (this one send the entire repo to replace the repo in client stores)

**Comment by meriadec** [comment]
can't wait.

**Comment by balthazar** [comment]
Me too!
