### ISSUE TITLE
make graph snapshot and use it in repo list

### ISSUE THREAD

**Issue by meriadec** [SIGSEV/Starveller#4]
- [x] create a route which show only the graph for one repo
- [x] use node-webshot to generate a snapshot based on this route
- [x] resize image (graphicmagick, sharp, or whatever)
- [x] store it in a dedicated mongo collection (or in the same, dont care)
- [x] make snapshot generate each time repos stars are updated
- [x] display snapshots in repo lists (home, and browse routes)

**Comment by balthazar** [comment]
There's still a bug though, it appears only on some repos but don't really know where it comes from..
