### ISSUE TITLE
Alerts system

### ISSUE THREAD

**Issue by meriadec** [SIGSEV/Starveller#6]
- [ ] create a reducer to handle messages, will look like an array or something. the messages will have:
  - an unique id (for painless removal), so let's use https://github.com/dylang/shortid
  - a type, like 'error', 'warning', 'info'
  - a content, which could be a string, or a react element
- [x] handle actions, like ADD_MESSAGE, REMOVE_MESSAGE to effectively add/remove messages in the array
- [x] create an action which dispatch ADD_MESSAGE, then dispatch REMOVE_MESSAGE after a timeout
- [x] create a component connected to the reducer, always visible and fixed to a corner, or something, and which display the messages list
- [x] make message 'dismissables' by click, so handle the case message is not here in REMOVE_MESSAGE triggered by the timeout

**Comment by balthazar** [comment]
![57687674](https://cloud.githubusercontent.com/assets/6033345/12372198/7669b462-bc47-11e5-9206-28b6bfc422af.jpg)

**Comment by meriadec** [comment]
@sammedve if you got idea on how we should display them :D
