### ISSUE TITLE
Add progression to github worker

### ISSUE THREAD

**Issue by meriadec** [SIGSEV/Starveller#9]
We should send actual progression when fetching stars of a repo.
Some repo take long time to be fetched, so it would be cool to display progression (page by page) while on the repo page, instead of just having a loader for minutes.

**Comment by meriadec** [comment]
dunno who can do that... any idea @Apercu ?

**Comment by balthazar** [comment]
Hum... We need to contact someone who his a _beast_ with sockets... I heard someone started to code at 12 and work at Orange, maybe I can ask him to do that.

**Comment by meriadec** [comment]
![img_20160123_222511](https://cloud.githubusercontent.com/assets/315259/12537496/fbe00bee-c2c0-11e5-9996-05b4c68727bb.jpg)
